### ISSUE TITLE
Failed to parse ..docstr_converage if there is only one pattern

### ISSUE THREAD

**Issue by we-taper** [HunterMcGushion/docstr_coverage#10]
This is due to [this](https://github.com/HunterMcGushion/docstr_coverage/blob/84ee0008d54a2f28bcf6a927a72952cb9bb2aad6/docstr_coverage/coverage.py#L428) line:
```
ignore_names = tuple([line.split() for line in open(options.ignore_names_file).readlines() if ' ' in line])
```
Example configuration file:
```
.*test.*\.py
```

**Comment by HunterMcGushion** [comment]
Thanks for opening this issue! Unfortunately, I wasn't able to reproduce the error with single-line configuration files. Can you show me the full command you used when you got the error?

**Comment by we-taper** [comment]
Thanks for the reply.

I did not pass any arguments to it since I named the file `.docstr_coverage` which is the default option for `--docstr-ignore-file` ([here](https://github.com/HunterMcGushion/docstr_coverage/blob/cfea92e7dd444abc739d2500a89485ec00f3ae11/docstr_coverage/coverage.py#L383).

The error is caused by `if ' ' in line`, since there isn't a blank space ` ` in my configuration since, it is skipped and hence `ignore_names=[]`.

**Comment by killthekitten** [comment]
@we-taper based on your config, I believe you wanted to ignore all the tests files. This can be done with the `--exclude` option.

The `--docstr-ignore-file` does something else. It ignores functions per file. Every line then should consist of at least two patterns separated by spaces. The first one is the pattern that matches the file, and all the others filter out functions in that file.

I can totally get your frustration though. I recommend you to check out the original PR (#4), and maybe send a new one to support the format you are looking for.

**Comment by HunterMcGushion** [comment]
@we-taper, ahh I understand the problem now. In addition to @killthekitten's recommendation, you can append ` .*` to the end of the line in your configuration file to make it the following:
```
.*test.*\.py .*
```
Note the space before the added `.*`. This means to ignore all nodes (functions/classes/methods) in the file. This does not apply to the file docstring; however, that can be ignored via the `-f` CLI option

**Comment by we-taper** [comment]
I see. Now I got it. Thanks guys!
