### ISSUE TITLE
error: no such option: --fail-under

### ISSUE THREAD

**Issue by fabiosangregorio** [HunterMcGushion/docstr_coverage#13]
In the docs is mentioned the option `--fail-under=<int|float>, -F <int|float>` but using it via the CLI results in the following error:
```
>> docstr-coverage telereddit --fail-under=80
      Usage: docstr-coverage [options]
      docstr-coverage: error: no such option: --fail-under

>> docstr-coverage telereddit -F 80
      Usage: docstr-coverage [options]
      docstr-coverage: error: no such option: -F
```

Am I doing something wrong?

Version is `1.0.5`

**Comment by HunterMcGushion** [comment]
Thanks for reporting this, @fabiosangregorio! This feature hasn’t been released on PyPI yet, so you’d have to install the master branch from GitHub to use it at the moment. I’ll get the next version released as soon as possible. Sorry for the confusion!

**Comment by fabiosangregorio** [comment]
All right then, I'll install from master then, Thank you :)

**Comment by killthekitten** [comment]
@HunterMcGushion need any help with this one?

**Comment by killthekitten** [comment]
@fabiosangregorio the actual option is `--failunder`.

**Comment by HunterMcGushion** [comment]
Terribly sorry about the delay, @fabiosangregorio and @killthekitten! Yes, that's a good point, @killthekitten. Thank you for the offer to help, but I'll get the release done as soon as I review your PR #14! Again, I apologize for the delay.
