### ISSUE TITLE
Test fails when packaging with Nix

### ISSUE THREAD

**Issue by augustebaum** [HunterMcGushion/docstr_coverage#135]
Hi,

I'm trying to package this project for the [Nix](https://nix.dev/) project, to ensure software reproducibility. When I run the tests they all succeed except for one line: https://github.com/HunterMcGushion/docstr_coverage/blob/8825428bdbb265af037c3e13ea22fbbc78d53c69/tests/test_config_file.py#L126
When I try to print `ctx.params["paths"]` I end up with:
```py
('/tmp/tmp.u2S0MtgQsO/source/tests', '/tmp/tmp.u2S0MtgQsO/source/docstr_coverage')
```
so `"docstr_coverage"` is indeed found in one of the paths---just not the first one. Is the test correct?

Please let me know if you need any more information about this. It's nothing urgent since everything else works; I can just assume the test is wrong and ignore it. I just wanted to let you know.

Thanks for the software :)

**Comment by MiWeiss** [comment]
Hi @augustebaum 

Thanks for the report. I am not sure if I understand it correctly. If I run our test suite (as done e.g. [here](https://github.com/HunterMcGushion/docstr_coverage/pull/136) just a few seconds ago) no tests fail. This contradicts your report, doesn't it? 

Or is your report something nix specific - in that case I'd have to admit that I am not familiar with Nix and would particularly appreciate a PR to fix the issue ;-)

**Comment by augustebaum** [comment]
Thanks for letting me know so quickly! I'm guessing this is a Nix issue then, but I'll have to investigate this further to find out...
I'll close this then :)
