### ISSUE TITLE
--failunder fails if coverage is less than 100% in Github Workflows

### ISSUE THREAD

**Issue by fabiosangregorio** [HunterMcGushion/docstr_coverage#23]
Running the package with the `--failunder` option in a Github Workflow, the process exits with code 1 even when the total coverage percentage is above the threshold. The only case in which the process exits with 0 is when the coverage is 100%. 

This only happens in Github Workflows though, while running the command on my terminal works as expected.

Example (See [this Github workflow run](https://github.com/fabiosangregorio/telereddit/runs/762383189?check_suite_focus=true)):

```bash
>> docstr-coverage telereddit --exclude=tests --failunder=70 --skipinit --badge="./docs/images/docs_badge.svg"

Overall statistics for 26 files (skipped __init__ methods):
Docstrings needed: 97; Docstrings found: 96; Docstrings missing: 1
Total docstring coverage: 99.0%;  Grade: Excellent
telereddit/services/generic_service.py:11 in public method `postprocess`:
        D102: Missing docstring in public method
##[error]Process completed with exit code 1.
```

**Comment by killthekitten** [comment]
@fabiosangregorio are you sure the snippet you provided is the failing example?

From what I can see in the failing build, the `failunder` option is not even used:

```bash
  mkdir documentation-reports
  docstr-coverage telereddit --verbose=3 --exclude=tests --skipinit 2>&1 | tee ./documentation-reports/docstr-coverage.txt
  (pydocstyle telereddit 2>&1 | tee ./documentation-reports/pydocstyle-coverage.txt; exit ${PIPESTATUS[0]})
  python .github/workflows/scripts/docs.py
```

Looks like `exit ${PIPESTATUS[0]}` (`pydocstyle?`) is the reason.

**Comment by fabiosangregorio** [comment]
Wooops Sorry, I linked the wrong run. This is the correct one: https://github.com/fabiosangregorio/telereddit/runs/762318523?check_suite_focus=true#step:12:3

**Comment by killthekitten** [comment]
@fabiosangregorio thanks! Still, it seems that `docstr_coverage` exits without an error code:

```
Needed: 97  -  Found: 96  -  Missing: 1
Total coverage: 99.0%  -  Grade: Excellent
Docstring coverage badge saved to './docs/images/docs_badge.svg'
telereddit/services/generic_service.py:11 in public method `postprocess`:
        D102: Missing docstring in public method
```

It's an error from `pydocstyle`. Do I miss something here?

**Comment by fabiosangregorio** [comment]
Oh I see, you're right. I forgot about running pydocstyle in the same command, my bad 😅
This can be closed.

**Comment by HunterMcGushion** [comment]
Awesome! Thanks for looking into this, @killthekitten!
