### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ChristianSauer** [HunterMcGushion/docstr_coverage#27]
Hey, I noticed some improvements in master vs the latest release. Could you kindly release them? I would ease our CI flow considerably.
Thx!

**Comment by HunterMcGushion** [comment]
@ChristianSauer, absolutely! So sorry for making you ask! V1.2.0 was just released. You can see what's been added in [the changelog](https://github.com/HunterMcGushion/docstr_coverage/blob/master/CHANGELOG.md#120-2020-07-21). Thank you for your support!

**Comment by ChristianSauer** [comment]
THank you very much!
