### ISSUE TITLE
Allow skipping docstrings of private methods (that start with a single underscore)

### ISSUE THREAD

**Issue by cthoyt** [HunterMcGushion/docstr_coverage#31]
Private methods are conventionally named starting with a single underscore (`_`). They usually are not for use by end-users, and are often not documented. It would be nice if `docstr-coverage` could be configured to skip reporting on these functions.

I can imagine a very simple PR to add the functionality within an additional conditional in the following code block (and another `click.option()` in the CLI. Would you be willing to accept a PR for this?

https://github.com/HunterMcGushion/docstr_coverage/blob/906e023de3242cebf909b079e8d01e17077a2d4b/docstr_coverage/coverage.py#L203-L218

**Comment by HunterMcGushion** [comment]
Love it! I just reviewed your PR. Thanks for your work, @cthoyt!
