### ISSUE TITLE
[RFC] Deprecate CLI options to use kebab-case

### ISSUE THREAD

**Issue by HunterMcGushion** [HunterMcGushion/docstr_coverage#37]
If anyone has any thoughts/ideas on this, please feel free to comment (especially if you think this is a bad idea).

I'd like to convert all CLI options to use kebab-case. Specifically, this would affect the following options:
- `--skipmagic` -> `--skip-magic`
- `--skipfiledoc` -> `--skip-file-doc`
- `--skipinit` -> `--skip-init`
- `--skipclassdef` -> `--skip-class-def`
- `--followlinks` -> `--follow-links`
- `--failunder` -> `--fail-under`

We would need a deprecation cycle during which both the old and new names are usable, but a deprecation warning is logged when an old option is used. The problem is that, as far as I can tell, [Click](https://github.com/pallets/click) has no native way to deprecate options -- only entire commands.

Something like [this SO answer](https://stackoverflow.com/a/50402799/8936527) seems promising. However, I have some reservations about monkey-patching another open-source repo. Perhaps we could avoid some problems by pinning our `setup.py` to a specific Click version, but that also doesn't seem ideal. 

I'd appreciate hearing from anyone that has any ideas or opinions on this.

**Comment by HunterMcGushion** [comment]
@cthoyt, any thoughts?

**Comment by cthoyt** [comment]
I don't think overengineering this one is the way to go since they're all options anyway. You could introduce new options and do some logic inside the CLI function itself that takes the value coming from an old command and overwrites the new name if it's set. This wouldn't take more than a few minutes to code so I'll send a PR demonstrating my solution.

**Comment by HunterMcGushion** [comment]
Hahah very glad I asked! Thanks for being willing to put something together.
