### ISSUE TITLE
Support for analyzing Python 2 code?

### ISSUE THREAD

**Issue by wearpants** [HunterMcGushion/docstr_coverage#44]
Wasn't clear from the readme - is it possible to use this project to analyze Python 2 code (with current release or perhaps an older version)?

I'm working on upgrading a large existing code base, and docstring coverage would be a useful metric to guide my efforts.

**Comment by MiWeiss** [comment]
Hi there

Disclaimer: I'm not the maintainer - my answer could be complete bogus ;-)

`docstr-coverage` is built for python3 and heavily relies on the `ast` module. The `ast` module [can only handle for the version of python it is shipped with](https://stackoverflow.com/questions/26655818/how-to-parse-python-2-x-with-python-3-x-ast-module). Thus, without having tested it, I do not expect this to work seamlessly out of the box. But please feel free to try and tell me if it worked ;-)

Alternatively, the old, unmaintained python 2 version of this project may be of help here: https://bitbucket.org/DataGreed/docstring-coverage

Good luck with your upgrading...

**Comment by HunterMcGushion** [comment]
@wearpants, after attempting to install in a Python 2 virtual environment, I can confirm everything @MiWeiss said. Additionally, Click no longer supports Python 2, although I'm sure there are other issues that would need to be addressed to add support. 

I also think that @MiWeiss's suggestion of using the original, Python2-only [docstring-coverage](https://bitbucket.org/DataGreed/docstring-coverage/wiki/Home) repo. Like he said, though, it has not been maintained for quite a while as the last commit was in 2012. So I'm not sure how well it'll work for you. Good luck with the upgrade!

**Comment by HunterMcGushion** [comment]
I'm closing this as we don't plan on adding Python 2 support. I hope you find a solution that works for you, @wearpants.
