### ISSUE TITLE
No Python files Exit Code

### ISSUE THREAD

**Issue by epassaro** [HunterMcGushion/docstr_coverage#47]
Hi!

We're trying to make a GitHub workflow to integrate `docstr-coverage` as you can [see here](https://github.com/tardis-sn/tardis/pull/1409/files). In that workflow `docstr-coverage` is run just on the files modified on the pull request that triggered the workflow.

My problem is, if no `.py` file is modified on a PR, then the `No Python files` output also exits with code `123` making the Action fail (because is non-zero). I can workaround this by doing some bash stuff, but first I wanted to ask if maybe would be worth considering exiting with `0` if no `.py` files are found.

**Comment by MiWeiss** [comment]
I think this request is based on a very valid usecase and I do agree that `docstr-coverage` should allow 0-file inputs!

However, I do not really like the idea of directly changing the exit code: IMO, if I pass a wrong directory (leading to no files found), I would like `docstr-coverage` to fail. 

Hence, I see the benefits of both failing and passing if no files are found. This is in line with similar discussions in other linters as well, e.g. https://github.com/psf/black/issues/746, where a user requests the exact opposit. 

I would suggest taking a compromise:  Keep the current behavior as it is, but allow an additional flag `--allow-void`. If set to true, in case of no .py files found, a warning is printed but exit code 0 is returned.

@HunterMcGushion, what's your take on this? Whatever you decide, I consider this issue very relevant and am happy to provide a PR to fix it.

**Comment by HunterMcGushion** [comment]
@epassaro, thanks for bringing this up! Like @MiWeiss, I'm hesitant to change the default exit code.

I think @MiWeiss's suggestion of adding a new flag, which would print a warning and return an exit code of 0 when no `.py` files are found is a great idea! Would this be sufficient for your case, @epassaro?

**Comment by epassaro** [comment]
Yes, sure. Seems the right choice!

**Comment by HunterMcGushion** [comment]
Fantastic! @MiWeiss, thank you for offering to take this on!

**Comment by MiWeiss** [comment]
@eparasso please check out my comment in #48 (as you are not yet part of the pr discussion, you probably did not receive a notification)

**Comment by epassaro** [comment]
If you are interested, we recently merged the `docstr-coverage` pipeline: https://github.com/tardis-sn/tardis/blob/master/.github/workflows/docstr-coverage.yml

**Comment by MiWeiss** [comment]
Great :-) I'll definitely keep a pointer to your workflow. What a beautiful application of `docstr-coverage`!

**Comment by HunterMcGushion** [comment]
Thanks a lot for sharing, @epassaro!
