### ISSUE TITLE
Question: github action diff docstr_coverage

### ISSUE THREAD

**Issue by jmaunon** [HunterMcGushion/docstr_coverage#60]
This is an open question: Have you though about how to use `docstr_coverage` on a Pull Request?
I mean, I was thinking to deny a PR if the PR reduces the `docstr_coverage` in a given %. In order to do that it would be needed to compare the branches. 
Do you have an idea if this is feasible?
Thanks!

**Comment by MiWeiss** [comment]
Hi @jmaunon 

Thanks a lot for your question. This is already possible. Have a look at this beautiful action, doing exactly what you want: https://github.com/tardis-sn/tardis/blob/master/.github/workflows/docstr-coverage.yml

I'm also working on a ready-to-use github action (a docstr-coverage wrapper) facilitating cool things like this, and more. Stay tuned ;-)

**Comment by jmaunon** [comment]
Thanks!
