### ISSUE TITLE
PyPi version not current (missing -d option)

### ISSUE THREAD

**Issue by afparsons** [HunterMcGushion/docstr_coverage#7]
Installed from PyPi:
`$ pip install docstr-coverage`

Checked version:
`$ pip show docstr-coverage`

```
Name: docstr-coverage
Version: 1.0.4
Summary: Utility for examining python source files to ensure proper documentation. Lists missing docstrings, and calculates overall docstring coverage percentage rating
Home-page: https://github.com/HunterMcGushion/docstr_coverage
Author: Hunter McGushion
Author-email: hunter@mcgushion.com
License: MIT
...
````

`$ docstr-coverage -d <...>`

```
Usage: docstr-coverage [options]

docstr-coverage: error: no such option: -d
```
It appears that this feature was added in [May 2019](https://github.com/HunterMcGushion/docstr_coverage/commit/0c3fd2e93226d15acde9f1637ca68fa47553a676) but the latest PyPi release was in April 2019.

**Comment by HunterMcGushion** [comment]
Thanks for the heads-up, @afparsons, and I apologize for the delay. Once I merge #6, I'll prepare the next release.

**Comment by HunterMcGushion** [comment]
I'm closing this because it's old and should no longer be a problem. Feel free to reopen if you think this was closed in error.
