### ISSUE TITLE
-d option prevents level 3 verbosity

### ISSUE THREAD

**Issue by afparsons** [HunterMcGushion/docstr_coverage#8]
I might be doing something wrong, but it seems that the verbose output for levels `2` and `3` are the same when using option `-d`. 

Installed on 15 November 2019 via:
`pip install git+https://github.com/HunterMcGushion/docstr_coverage.git`

I've created a regex ignore file `docstr_ignore.txt` containing this single line:
```
.* __.+__
```

I've run the program with both levels of verbosity:
`$ docstr-coverage -m -d ~/Development/docstr_ignore.txt -e "migrations/*" -v 2 . > 2.txt`
`$ docstr-coverage -m -d ~/Development/docstr_ignore.txt -e "migrations/*" -v 3 . > 3.txt`

And their outputs are basically equivalent. 
`$ diff 2.txt 3.txt`

```
404a405
>  - No module docstring
413a415
>  - No module docstring
545a548
>  - No module docstring
```

Notably, if I remove the `-d` option and `diff` the two outputs, the levels of verbosity are as expected—`3` provides many more details than `2`.

**Comment by HunterMcGushion** [comment]
Thanks for opening this, @afparsons! 
Just to clarify on your last statement, are you saying that `-v` behaves as expected without `-d`? Then the addition of `-d` messes with `-v`?

Would you be able to paste a minimal example python file so I can reproduce your results? Or do you see similar results if we run this against the library's own `coverage.py` file as an example?

**Comment by afparsons** [comment]
Hi @HunterMcGushion, 

> Just to clarify on your last statement, are you saying that -v behaves as expected without -d? Then the addition of -d messes with -v?

Yes, exactly that. It sounds strange, but there might be some control flow bug somewhere. 

> Would you be able to paste a minimal example python file so I can reproduce your results?

I was running this against a large internal project...I'll try to find some postable code to run this against. I did not try running this using the `coverage.py` file.

**Comment by econchick** [comment]
I have the same issue:

```sh
$  docstr-coverage -v 3 src/metrics

File: "src/metrics/dispatcher.py"
 - No docstring for `BaseMetricDispatcher.__init__`
 - No docstring for `BaseMetricDispatcher._setup_metric_relay`
 - No docstring for `BaseMetricDispatcher._setup_metric_key`
 - No docstring for `BaseMetricDispatcher.logger`
 - No docstring for `BaseMetricDispatcher._submit_callback`
 - No docstring for `BaseMetricDispatcher.submit`
 - No docstring for `CounterDispatcher._setup_metric_relay`
 - No docstring for `GaugeDispatcher._setup_metric_relay`
 - No docstring for `TimerDispatcher.__init__`
 - No docstring for `TimerDispatcher._setup_metric_relay`
 - No docstring for `TimerDispatcher.__enter__`
 - No docstring for `TimerDispatcher.__exit__`
 Needed: 21; Found: 9; Missing: 12; Coverage: 42.9%

File: "src/metrics/client.py"
 - No docstring for `MetricsRegistry.__init__`
 Needed: 8; Found: 7; Missing: 1; Coverage: 87.5%
# <--snip-->

$ docstr-coverage -v 3 -d docstr_ignore.txt src/metrics

File: "src/metrics/dispatcher.py"
 Needed: 11; Found: 9; Missing: 2; Coverage: 81.8%

File: "src/metrics/client.py"
 Needed: 7; Found: 7; Missing: 0; Coverage: 100.0%
# <--snip-->
```

**Comment by HunterMcGushion** [comment]
Hi, @afparsons and @econchick! Sorry it took far too long for me to get to this, but could you check out PR #19 (WIP) to see if it solves your problems? You should be able to install that branch with the following command:
```bash
pip install git+https://github.com/HunterMcGushion/docstr_coverage.git@bug/docstr-ignore-file-verbose-3
```

I'm in the process of polishing everything up and adding regression tests, so if it looks good to you, we can release soon. Thank you both for your very helpful reports and your patience!

**Comment by HunterMcGushion** [comment]
I went ahead and merged the fix, but if either of you are still experiencing the bug, please feel free to reopen this issue!
