### ISSUE TITLE
Doc generation tool

### ISSUE THREAD

**Issue by arita37** [HunterMcGushion/docstr_coverage#9]
What do you think of this light-weight doc generating tool ?

https://github.com/arita37/cli_code/tree/dev/

**Comment by HunterMcGushion** [comment]
Thanks for sharing your tool, @arita37! It sounds really cool, but I cant really tell exactly what it does. It'd be immensely helpful to put an example of what your tool does in your repo's README. A simple before and after would make a huge difference and help people understand how to use your tool. I'm going to close this issue as it isn't related to `docst_coverage`, but if you want to continue discussing your repo, feel free to keep commenting here or reach contact me directly. Good luck developing your tool!

**Comment by arita37** [comment]
There are few utilities :

one of these
 cli_docs  myrepo

generates the list of signatures for one repo
  classname.methodname(....)

Very useful when you have new unknown code.


Others are auto-install of package
from code source parsing....
